import { PRICE_PATTERN } from '../../../utils/commerce.js';

export default {
    FeatureName: 'M@S Studio - Variations Page',
    features: [
        {
            tcid: '0',
            name: '@studio-create-variation-editor',
            path: '/studio.html',
            browserParams: '#page=fragment-editor&path=nala&fragmentId=',
            data: {
                cardid: '6f189be0-d64b-468f-b340-92888206cce8',
                locale: 'en_CA',
                localeName: 'Canada',
                price: PRICE_PATTERN.CA.mo,
                priceUS: PRICE_PATTERN.US.mo,
            },
            tags: '@mas-studio @regional-variations',
        },
        {
            tcid: '1',
            name: '@studio-create-variation-table-view',
            path: '/studio.html',
            browserParams: '#page=fragment-editor&path=nala&fragmentId=',
            data: {
                cardid: '6f189be0-d64b-468f-b340-92888206cce8',
                locale: 'en_CA',
                localeName: 'Canada',
                price: PRICE_PATTERN.CA.mo,
            },
            tags: '@mas-studio @regional-variations',
        },
        {
            tcid: '2',
            name: '@studio-create-variation-new-fragment',
            path: '/studio.html',
            browserParams: '#page=content&path=nala',
            data: {
                osi: 'yIcVsmjmQCHKQ-TvUJxH3-kop4ifvwoMBBzVg3qfaTg',
                variant: 'plans',
                locale: 'en_CA',
                localeName: 'Canada',
                price: PRICE_PATTERN.CA.mo,
            },
            tags: '@mas-studio @regional-variations',
        },
        {
            tcid: '3',
            name: '@studio-delete-variation',
            path: '/studio.html',
            browserParams: '#page=fragment-editor&path=nala&fragmentId=',
            data: {
                cardid: '6f189be0-d64b-468f-b340-92888206cce8',
                locale: 'en_CA',
                localeName: 'Canada',
                price: PRICE_PATTERN.CA.mo,
            },
            tags: '@mas-studio @regional-variations',
        },
        {
            tcid: '4',
            name: '@studio-variation-locales-US',
            path: '/studio.html',
            browserParams: '#page=fragment-editor&path=nala&fragmentId=',
            data: {
                cardid: '6f189be0-d64b-468f-b340-92888206cce8',
                locales: {
                    en_GB: 'United Kingdom',
                    en_AU: 'Australia',
                    en_IN: 'India',
                },
            },
            tags: '@mas-studio @regional-variations',
        },
        {
            tcid: '5',
            name: '@studio-variation-locales-GB',
            path: '/studio.html',
            browserParams: '#locale=en_GB&page=fragment-editor&path=nala&fragmentId=',
            data: {
                cardid: 'afddc0f8-c88f-4be7-b515-9f9e8127dc3d',
                locales: {
                    en_AU: 'Australia',
                    en_IN: 'India',
                },
            },
            tags: '@mas-studio @regional-variations',
        },
        {
            tcid: '6',
            name: '@studio-variation-override-restore',
            path: '/studio.html',
            browserParams: '#page=fragment-editor&path=nala&fragmentId=',
            data: {
                cardid: '287ef7ee-b0e3-4d95-a689-578de492ceae',
                locale: 'en_CA',
                localeName: 'Canada',
                original: {
                    title: 'Nala Automation Card with Variation',
                    badge: 'DO NOT EDIT',
                    description: 'MAS Automation Test card.',
                    iconURL: 'https://www.adobe.com/content/dam/shared/images/product-icons/svg/illustrator.svg',
                    callout: '',
                    promoText: '',
                    whatsIncludedText: '',
                    badgeColor: { name: 'Yellow 300', css: 'rgb(255, 255, 0)' },
                    badgeBorderColor: { name: 'Default', css: 'rgb(255, 255, 0)' },
                    borderColor: { name: 'Gray 300', css: 'rgb(218, 218, 218)' },
                    price: PRICE_PATTERN.EG.mo,
                    strikethroughPrice: PRICE_PATTERN.EG.mo,
                    ctaLabel: 'Buy now',
                    osi: 'yIcVsmjmQCHKQ-TvUJxH3-kop4ifvwoMBBzVg3qfaTg',
                    osiTags: { offerType: 'offer_type/base', marketSegment: 'market_segments/com', planType: 'plan_type/m2m' },
                },
                title: '[var] Edited title',
                badge: '[var] Edited badge',
                description: '[var] Edited description',
                iconURL: 'https://www.adobe.com/cc-shared/assets/img/product-icons/svg/photoshop.svg',
                callout: '[var] Callout text',
                promoText: '[var] Promo text',
                whatsIncludedText: '[var] Whats included',
                badgeColor: { name: 'Green 900', css: 'rgb(5, 131, 78)' },
                badgeBorderColor: { name: 'Green 900', css: 'rgb(5, 131, 78)' },
                borderColor: { name: 'Gray 300', css: 'rgb(218, 218, 218)' },
                price: PRICE_PATTERN.EG.mo,
                ctaLabel: '[var] CTA label',
                osi: 'XTzr-NReoRxcsGKF7WMHBJ_pLC8r6K9dclKiEgFxbUc',
                osiTags: {
                    offerType: 'offer_type/trial',
                    marketSegment: 'market_segments/edu',
                    planType: 'plan_type/puf',
                },
            },
            tags: '@mas-studio @regional-variations',
        },
        {
            tcid: '7',
            name: '@studio-create-variation-GB',
            path: '/studio.html',
            browserParams: '#locale=en_GB&page=content&path=nala',
            data: {
                osi: 'yIcVsmjmQCHKQ-TvUJxH3-kop4ifvwoMBBzVg3qfaTg',
                variant: 'plans',
                locale: 'en_AU',
                localeName: 'Australia',
                price: PRICE_PATTERN.AU.mo,
            },
            tags: '@mas-studio @regional-variations',
        },
        {
            tcid: '8',
            name: '@studio-variation-selfreference',
            path: '/studio.html',
            browserParams: '#page=fragment-editor&path=nala&fragmentId=',
            data: {
                cardid: '6f189be0-d64b-468f-b340-92888206cce8',
                locale: 'en_CA',
                localeName: 'Canada',
                price: PRICE_PATTERN.CA.mo,
                referencesBaseUrl: 'https://odinpreview.corp.adobe.com/adobe/contentFragments',
                editedTitle: '[selfref] Edited title',
            },
            tags: '@mas-studio @regional-variations',
        },
    ],
};
