name: IO WWW Merge
on:
    pull_request:
        types: [closed]
        paths:
            - 'io/www/**'

jobs:
    build_and_test:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: io/www
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22.x'
                  cache: 'npm'
                  cache-dependency-path: io/www/package.json

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm test

    deploy_stage:
        needs: build_and_test
        uses: ./.github/workflows/io-deploy.yaml
        secrets:
            ENV_CONTENT: ${{ secrets.AIO_WWW_ENV_STAGE }}
            AIO_CONTENT: ${{ secrets.AIO_WWW_AIO_STAGE }}

    test_stage:
        needs: deploy_stage
        uses: ./.github/workflows/io-tests.yaml
        secrets:
            workspace: ${{ secrets.AIO_NS_STAGE }}

    deploy_production:
        needs: test_stage
        uses: ./.github/workflows/io-deploy.yaml
        secrets:
            ENV_CONTENT: ${{ secrets.AIO_WWW_ENV_PROD }}
            AIO_CONTENT: ${{ secrets.AIO_WWW_AIO_PROD }}

    test_production:
        needs: deploy_production
        uses: ./.github/workflows/io-tests.yaml
        secrets:
            workspace: ${{ secrets.AIO_NS_PROD }}
