name: IO WWW PR Check
on:
    pull_request:
        types: [opened, synchronize, reopened]
        paths:
            - 'io/www/**'

jobs:
    tests:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: io/www

        strategy:
            matrix:
                node-version: [22.x]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
                  cache-dependency-path: io/www/package.json

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm test

    deploy:
        needs: tests
        if: success() && github.event_name == 'pull_request'
        uses: ./.github/workflows/io-deploy.yaml
        secrets:
            ENV_CONTENT: ${{ secrets[format('AIO_WWW_ENV_{0}', github.actor)] }}
            AIO_CONTENT: ${{ secrets[format('AIO_WWW_AIO_{0}', github.actor)] }}

    test-deployed:
        needs: deploy
        if: success() && github.event_name == 'pull_request'
        uses: ./.github/workflows/io-tests.yaml
        secrets:
            workspace: ${{ secrets[format('AIO_NS_{0}', github.actor)] }}
