name: IO Studio Merge
on:
    pull_request:
        types: [closed]
        paths:
            - 'io/studio/**'

jobs:
    deploy_stage:
        if: github.event.pull_request.merged == true
        uses: ./.github/workflows/io-studio-deploy.yaml
        with:
            batch_size: 10
            rps_limit: 20
        secrets:
            ENV: ${{ secrets.AIO_STUDIO_ENV_STAGE }}
            AIO: ${{  secrets.AIO_STUDIO_AIO_STAGE }}
            ODIN_BUCKET: ${{ secrets.ODIN_BUCKET_STAGE }}

    test_stage:
        needs: deploy_stage
        uses: ./.github/workflows/io-studio-tests.yaml
        secrets:
            workspace: ${{ secrets.AIO_STUDIO_NS_STAGE }}

    deploy_production:
        needs: test_stage
        uses: ./.github/workflows/io-studio-deploy.yaml
        with:
            batch_size: 10
            rps_limit: 20
        secrets:
            ENV: ${{ secrets.AIO_STUDIO_ENV_PROD }}
            AIO: ${{  secrets.AIO_STUDIO_AIO_PROD }}
            ODIN_BUCKET: ${{ secrets.ODIN_BUCKET_PROD }}

    test_production:
        needs: deploy_production
        uses: ./.github/workflows/io-studio-tests.yaml
        secrets:
            workspace: ${{ secrets.AIO_STUDIO_NS_PROD }}
